baseurl: ""
url: "http://clayell.is"
title: "clayell.is"
favicon: "assets/images/favicon.ico"
headshot: "assets/images/headshot.png"
first_name: "clay"
last_name: "ell.is"
description: >-
  Hi, I'm Clay ðŸ‘‹ I'm an iOS engineer with 10 years of
  experience designing, developing, and deploying over 15 apps.
email: "clayellis@me.com"
github_username:  "clayellis"
resume: "assets/docs/Clay Ellis - Sr. iOS Engineer Resume.pdf"

#theme: minima
#plugins:
#  - jekyll-seo-tag
#  - jekyll-feed